name: Build LibreOffice Android

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            openjdk-17-jdk \
            python3 \
            git \
            g++ \
            make \
            ninja-build \
            unzip \
            wget

      - name: Download Android SDK/NDK
        run: |
          mkdir -p $HOME/android-sdk
          cd $HOME/android-sdk
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip commandlinetools-linux-9477386_latest.zip -d cmdline-tools
          yes | cmdline-tools/bin/sdkmanager --sdk_root=$HOME/android-sdk "platform-tools" "platforms;android-34" "ndk;26.1.10909125"

      - name: Configure LibreOffice
        run: |
          ./autogen.sh \
            --with-distro=LibreOfficeAndroid \
            --with-android-ndk=$HOME/android-sdk/ndk/26.1.10909125 \
            --with-android-sdk=$HOME/android-sdk \
            --enable-android-app \
            --disable-ccache

      - name: Build LibreOffice
        run: |
          make

      - name: Upload build output
        uses: actions/upload-artifact@v4
        with:
          name: libreoffice-android-build
          path: instdir
