name: Build LibreOffice Android (CI)

on:
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # ✅ 修正 ninja 包名为 ninja-build
      - name: Install basic deps
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git build-essential ninja-build python3 python3-pip openjdk-17-jdk \
            pkg-config autoconf automake libtool zip unzip curl wget \
            libgl1-mesa-dev libx11-dev libxi-dev libxext-dev libxrender-dev

      - name: Setup Android SDK & NDK
        run: |
          mkdir -p $HOME/android-sdk
          cd $HOME/android-sdk
          curl -fsSLO https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip -q commandlinetools-linux-9477386_latest.zip
          mkdir -p cmdline-tools/latest
          mv cmdline-tools/* cmdline-tools/latest/ || true
          yes | ./cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/android-sdk --licenses
          yes | ./cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/android-sdk \
            "platform-tools" "platforms;android-34" "build-tools;34.0.0" "ndk;25.2.9519653"

      - name: Set environment vars
        run: |
          echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
          echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
          echo "ANDROID_NDK_HOME=$HOME/android-sdk/ndk/25.2.9519653" >> $GITHUB_ENV
          echo "JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64" >> $GITHUB_ENV

      - name: Build LibreOffice for Android
        working-directory: ${{ github.workspace }}
        env:
          ANDROID_SDK_ROOT: ${{ env.ANDROID_SDK_ROOT }}
          ANDROID_HOME: ${{ env.ANDROID_HOME }}
          ANDROID_NDK_HOME: ${{ env.ANDROID_NDK_HOME }}
          JAVA_HOME: ${{ env.JAVA_HOME }}
        run: |
          echo "=== Starting LibreOffice Android build ==="
          if [ -d "android" ]; then
            cd android
          fi
          if [ -f "./gradlew" ]; then
            chmod +x ./gradlew
            ./gradlew assembleDebug --stacktrace || true
          else
            echo "gradlew not found, using fallback make"
            make -C android || true
          fi

      - name: Archive build outputs
        if: success()
        run: |
          mkdir -p artifacts
          find . -type f -name "*.apk" -exec cp {} artifacts/ \; || true
          find . -type f -name "*.aab" -exec cp {} artifacts/ \; || true
          find . -type f -name "*.so" -exec cp {} artifacts/ \; || true

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: libreoffice-android-build
          path: artifacts/
